### ISSUE TITLE
Add support to retain "locale" URL parameter

### ISSUE THREAD

**Issue by MrNicodemuz** [BeSimple/BeSimpleI18nRoutingBundle#52]
I need the ability to generate URLs with a locale URL parameter:
api.domain.com/v1/object?foo=bar&locale=en

Currently, it seems like the locale parameter is being unset in:
https://github.com/BeSimple/BeSimpleI18nRoutingBundle/blob/c0e0d95134a0c60144f3f87d56ce451e12124021/Routing/Router.php#L52

**Comment by boekkooi** [comment]
Hi @MrNicodemuz 

I would advice not to use routes of `type: be_simple_i18n` for your API that would fix your problem another option would be to override `BeSimple\I18nRoutingBundle\Routing\Router::generate` and remove the unset. 

Since removing the 'locale' is needed for not having it appear in the generate url this is not fixable without a massive BC break.
